# Workshop activities and presentations

The workshop was facilitated by its two co-chairs and included a number of presentations from DFO personel and external experts (Table \ref{tab:talks}, which contains links to the different presentations). Plenary presentations were followed by discussions between workshop participants on the topics at hand, with the main goal of exchanges being to openly share knowledge and to reach agreement on what constitutes "best practices" for age estimation using hard parts.

As part of the workshop planning, participants were asked to provide a summary of physical collections of hard structures and to identify the programs that were involved in the collection and analysis of ages using these structures. Given the large number of taxa for which age estimation materials are collected by different regions of Fisheries and Oceans Canada (Figure \@ref(fig:fighistogram)), the recommended best practices from this workshop involve programs spanning the whole country, and concern marine stocks in the Atlantic, Arctic and Pacific oceans, as well as a number of diadromous and freshwater species. The recommended best practices also apply to a number of different structures, including otoliths, scales, vertebrae and mollusc shells (Table \@ref(tab:homework)).

## Day 1 - Basics of age estimation {#sec:day1}

The first day covered the basics of age estimation. The literature on research associated with otoliths is vast and varied. Peter Comeau gave a presentation on the history and realities of age estimation of marine organisms (link to presentation appears in Table \ref{tab:talks}). His presentation highlighted the importance of age estimation in stock assessments. He also pointed out that there once was a stigma associated with jobs that involved age estimation, they were perceived as an entry-level position with a low retention rate, whereas the reality is that they require a unique skill set, considerable experience and are essential to scientific inquiries related to fish population dynamics.

Julie Coad Davies gave an overview of the age estimation activities that she is involved in, in her role as lab manager for DTU Aqua and also through her chairing the International Council for the Exploration of the Sea (ICES) Working Group on SmartDots Governance ([WGSMART](https://www.ices.dk/community/groups/Pages/WGSMART.aspx)) and the ICES Working Group on Biological Parameters ([WGBIOP](https://www.ices.dk/community/groups/Pages/WGBIOP.aspx)) (link to presentation appears in Table \ref{tab:talks}). Julie highlighted the importance of clear communication between laboratories and the paramount role of exchanges of both physical otoliths and digital images to identify potential age estimation biases that may exist between laboratories. Similarly, the ICES working groups have in their mandate the formulation of shared methodologies and protocols and provide guidelines for how to best captures information on biological parameters and how to conduct otolith exchanges between laboratories [@ICES:BIOP].

Stephen Wischniowski shared his experience of running an age estimation laboratory (the [Sclerochronology Lab](https://www.pac.dfo-mpo.gc.ca/science/species-especes/agelab-scalimetrie/index-eng.html) at the Pacific Biological Station) and being involved in the Committee of Age Reading Experts ([CARE](https://care.psmfc.org/)) (link to presentation appears in Table \ref{tab:talks}). The demands for age estimation services from the lab far exceed its ability to process samples and a "quota" is imposed on the number of otoliths that the lab can process. The lab technicians are taught the intricacies associated with age estimation from all types of species and structures. Stephen estimates that it takes five years to train a technician to the point where they can reliably estimate ages for a range of species and can teach others.

Sylvie Robichaud and Karen Robertson presented the procedures associated with age estimation of Atlantic Herring in the Gulf Region (link to presentation appears in Table \ref{tab:talks}). There are two spawning components that must first be distinguished from each other before age estimates can be made. The morphology of otoliths is used to distinguish between spawning components and the number of annuli and the date of capture are then integrated into an age estimate. The otoliths come from a variety of sources, ranging from research surveys to experimental fishing and from commercial fisheries. The laboratory protocols used to process samples require the extraction of otoliths, which are subsequently mounted in epoxy resin, photographed, and are then used for age estimation. 

Kim Emond and Hélène Dionne presented the procedures associated with age estimation of Atlantic Herring in the Québec Region.The otolith based techniques to decipher between spring spawning and fall spawning herring stocks of Atlantic Herring used by the Québec region were explained and shown (link to presentation appears in Table \ref{tab:talks}). Similarities were seen between approaches used by the technicians in the Gulf region and those in the Québec region both for estimating Herring ages and spawning component assignment. The stock assessment for this stock relies on a variety of data sources and on a comprehensive sampling of otoliths. Ages determined from otoliths are essential to the stock assessment as they are a precursor for many important population model inputs such as the catch-at-age. 

Tania Davignon-Burton gave a talk of reconciling expectations and realities in a age estimation production environment (link to presentation appears in Table \ref{tab:talks}). There are often high expectations for estimating ages using otoliths, but the laboratory activities required to obtain age estimates mean that some prioritisation must take place. In essence, it is not always quick and easy to age otoliths, it takes time and often demand outweighs technician time.

During the question period there were discussions pertaining to the importance of cleaning and storing hard structures appropriately. It was highlighted that clean otoliths are required for taking high quality pictures that are optimal for age estimation. Previously some labs had stored otoliths in glycerin solutions, however there was a consensus that it is better to store otoliths dry, as this is better for otolith preservation, reading of older otoliths, otolith microchemistry and isotopes. Several participants agreed it is best to clean otoliths immediately upon extraction, dry appropriately, and store dry, as this is best for age estimation, microchemistry and isotopic analyses. If otoliths are soaked in a solution such as glycerin to improve contrast and the readability of annuli, the otoliths should be cleaned, dried and stored dry after reading to avoid deterioration.

Tracey Loewen and Rick Wastle presented their work on estimating ages of difficult-to-age species and otolith microchemistry techniques used for age estimation (link to presentation appears in Table \ref{tab:talks}). They explained that their Otolith Ageing Lab at the Freshwater Institute in Winnipeg is responsible for age estimation of 32 species found in the Arctic, including but not limited to Arctic Char (*Salvelinus alpinus*), Dolly Varden (*Salvelinus malma*), Lake Trout (*Salvelinus namaycush*), Greenland Halibut (*Reinhardtius hippoglossoides*), Redfish (*Sebastes*) and Arctic Cod (*Boreogadus saida*). Otolith microchemistry techniques are used to support and validate age estimation technique, such as annual Zinc markers that align with growth rings on otoliths. Rick Wastle went in depth on approaches used to age Greenland Halibut in the Arctic as this species is difficult to age because of its slow growth. Despite the difficulty with estimating ages for the species, the lab persisted, testing a wide range of approaches before settling on what is perceived as the best and appropriate age estimation methods. The methods that they developed improve the understanding of growth patterns for the species. They elaborated that Strontium Calcium (SrCl) marking was used to try and validate growth rings with moderate success, and concluded sectioning the left otolith bulge as well as longitudinal sectioning have advantages for estimating ages in this slow growing species. 

Daniel Ricard presented the Standard Operating Procedures (SOP) document used in the Gulf Region. This document is meant as a central point for any person seeking information about age estimation in the Gulf Region. The SOP document contains detailed information concerning the collection, preparation, age estimation and storage of age structures for fish species that are used for age estimation in the Gulf region. The summary of otolith collections held by the Gulf Region and available as OpenData records was also presented and suggested as a starting point for documenting physical collections, including reference collections.
