## Day 2 - Digital imaging of ageing structures {#sec:day2}

The second day of the workshop focused on topics related to the capture of digital images of ageing structures, how to annotate, and common software to store and manipulate images. 

The day started with a tour of the laboratory facilities used in age estimations at the Gulf Fisheries Centre. The laboratories used for age estimation of Atlantic Cod (*Gadus morhua*), White Hake (*Urophycis tenuis*), American Plaice (*Hippoglossoides platessoides*), Witch Flounder (*Glyptocephalus cynoglossus*), Winter Flounder (*Pseudopleuronectes americanus*), Yellowtail Flounder (*Limanda ferruginea*) and Atlantic Herring (*Clupea harengus*). The facilities used for imaging whole otoliths mounted in epoxy and imaging of whole otoliths were visited and participants had the opportunity to ask questions and try the tools and software used by their Gulf Region colleagues. Participants also visited the Atlantic Cod, American Plaice, Winter Flounder, Yellowtail Flounder and Atlantic Herring otolith collections, had the opportunity to see the vast amounts of otoliths stored at the Gulf Fisheries Centre and see how the ageing structures are stored and archived. 

A presentation about *SmartDots* from external expert Julie Coad Davies showed how this tool is being used for otolith exchanges between laboratories in Europe (link to presentation appears in Table \ref{tab:talks}). The development of the *SmartDots* application is managed by ICES Working Group on SmartDots Governance ([WGSMART](https://www.ices.dk/community/groups/Pages/WGSMART.aspx)) in close collaboration with the ICES Secretariat as well as national fisheries laboratories. *SmartDots* and its associated website provide a set of software tools to support users in managing all data of ICES biological reading (like age, maturity, larvae identification) workshops and exchanges [@ICES:SMART]. There was tangible interest among DFO employees to use *SmartDots*. Several people noted the value of being able to exchange digital otoliths and provide several annotations/reader interpretations on an otolith image, to compare and contrast the patterns identified by technicians and help in recording authoritative interpretations of otolith images. This would also allow cross-region comparisons where technicians from other regions estimate the age of an individual using otolith images, hence providing cross-region comparisons of age interpretation. This approach would help house ageing structure interpretations in one common place. 

Karen Robertson gave a presentation on taking good images of otoliths, which could be transferable to other ageing structures (link to presentation appears in Table \ref{tab:talks}). She showed how it is important to have a reliable workspace with appropriate lighting and a microscope equipped with a digital camera. The image capture can be done in a number of softwares, including the one provided by the microscope manufacturer, the Leica *LAS X* software suite. Karen also pointed out the importance of having a well-defined naming convention for images and a strict protocol for file storage. Image processing is an important step to improve the readability of otolith images and a number of filtering options are available. There were brief discussions on what the appropriate naming convention should be and consensus among the group that this should be standardised when possible. 

David Fishman presented options for developing a storage solution for otolith/ageing structure images in the form of *DFO Dots*, an application which can be integrated with *SmartDots*. A discussion about *DFO Dots* followed. Participants felt that having access to a tool that helps in managing otolith collections, curating reference collections and supporting age estimation tasks would be beneficial to their work. There was enthusiastic support for further development of *DFO Dots* among the workshop participants. Of particular relevance to the earlier presentation by Julie Coad Davies is the seamless integration of *SmartDots* in the the *DFO Dots* application through the use of the Application Programming Interface (API) required by *SmartDots*.

A group discussion on the reporting features of *SmartDots* and how the tool can be used for obtaining growth increments followed. Participants noted the value of having annotated imaged otoliths and being able to readily generate quick reports in *SmartDots* to rapidly assess results of age reading runs. 

Others, particularly those in production ageing labs noted capturing digital images of ageing structures adds time to the laboratory process used to obtain age estimates. It is unclear whether the benefits of obtaining digital images of ageing structures outweighs the costs associated with the additional time required. 
To address this it was suggested that as a starting point, a reference collection should be imaged. Having a reference collection of imaged otoliths/ageing structures allows researchers to document examples of what otoliths/ageing structures of a particular age-class look like and to explain why classification of being a different age would be incorrect. Reference collections are also useful for training new readers and for providing continuity in ageing methodologies when there are discontinuities in an age estimation program (e.g. times when there is no overlap between new and former readers).  

Once digital images of ageing structures are available, an additional step is to annotate them. It was noted that it is probably impractical to annotate images in production ageing situations, but as a starting point the reference collection should be annotated in *SmartDots* or *DFO Dots*. This provides an authoritative record that can be used to better document the reference collection. If steps are done to facilitate more rapid imaging of otoliths and potentially automated annotations, such approaches could eventually be integrated into the workflow of production ageing labs. However, such advances are far off and the automation of image annotation can have major drawbacks, as annotation and reading of age structures takes significant expertise and can include some subjective decisions on unclear growth increments. 
