## Day 3 - Analysis of age estimates {#sec:day3}

The third day of the workshop focused on what is done with age estimates, namely the use of such data in fitting growth models and in computing catch-at-age matrices. Such applications of ageing data are often the backbone of stock assessment models, making their computation imperative for well informed estimates of population abundance and projections.

Daniel Ricard and Andrea Perreault gave presentations on growth models. Daniel Ricard showed how growth models are typically fit and gave examples of developing growth models for American Plaice. Daniel also showed how to effectively fit growth models for males and females and highlighted the importance of weighting observations to ensure that the model fitting accounted for the sampling design. Andrea Perrault gave a talk on the importance of accounting for length-stratified sampling when fitting growth models from survey data as length-stratified sampling can lead to biased estimates of growth model parameters [@Perreault-etal-2020-length-stratification]. Andrea went over several potential methods that can be used to account for length-stratified length sampling when fitting growth models and with simulations showed the method that leads to the least amount of bias. During the question period Andrea pointed out the risks of overestimating the asymptotic length in a von Bertalanffy growth model (often called $L_{infinity}$), which include overestimation of biomass and the potential perception that fish are bigger than they actually are, and this bias propagates through to the biomass estimates.

Lisa Ailloud from NOAA NMFS gave a presentation about age-length keys. She discussed the distinction between forward and reverse age-length keys, and provided an alternative hybrid methodology that was previously applied to bluefin tuna [@Ailloud-Hoenig-2019-theory; @Ailloud-etal-2019-bluefin]. She also described how to fill gaps in age-length keys when not enough information is available. 

Catch-at-age calculations presentation by Andrew Smith from the Quebec Region described his experience with trying to replicate catch-at-age calculations that were previously done in a bespoke software called *catch.exe*. An R package that was developed to compute catch-at-age matrices was also presented [@Ouellette-Plante-etal-2022-catchR]. Use of the package and cautions of trying to reproduce exact catch-at-age matrices from previous work that made several subjective decisions was shared. The catchR package was presented and it was shown how the package can reduce subjectivity in the computation of catch-at-age. 

Kim Emond from the Quebec Region presented the methodologies used in the herring stock assessment to compute catch-at-age matrices from commercial landings and from hydroacoustic surveys.Once again, Kim highlighted the need to reduce subjectivity in computations of catch-at-age, to document decisions and be consitent with decision making across years. 

Christopher Corriveau and Ellie Weise from Dalhousie University presented their work on using DNA methylation to estimate ages. The presentation provided an overview of this new methodology and highlighted a novel way forward for age estimation that could provide less reader subjectivity if refined and calibrated appropriately.

A group discussion finally took place to draft the recommendations that appears in section \@ref(sec:recommendations). The recommendations cover a variety of subjects, ranging from practical recommendations for age estimation to institutional recommendations that could foster the development of a community of age readers within DFO. 
