---
title: "Proceedings of the Technical Expertise in Stock Assessment (TESA) national workshop on 'Best practices in age estimation', 31 January to 02 February 2023 in Moncton, New Brunswick"
french_title: Titre ici (*Nom latin de l'espèce*)
year: 2024
report_number: nnn
author: |
  Daniel Ricard^1^,
  Peter Comeau^2^,
  Aaron Adamack^3^,
  Jacob Burbank^1^,
  Abby Daigle^1^,
  Allan Debertin^4^,
  Kim Emond^5^,
  Tracey Loewen^6^,
  Andrea Perreault^3^,
  Gregory Puncher^2^,
  Karen Robertson^1^,
  Nicolas Rolland^1^,
  Meredith Schofield^3^,
  Andrew Smith^5^,
  Francois-Étienne Sylvain^1^ and
  Stephen Wischniowski^7^
author_list: "Ricard, D., Comeau, P., Adamack, A., Burbank, J., Daigle, A., Debertin, A., Emond, K., Loewen, T., Perreault, A., Puncher, G., Robertson, K., Rolland, N., Schofield, M., Smith, A., Sylvain, F.-É. and Wischniowski, S."
region: Gulf Region
french_region: Région du Golfe
isbn: "ISBN GOES HERE"
address: |
  ^1^Gulf Fisheries Centre, Fisheries and Oceans Canada, 343 Université Avenue, Moncton, New Brunswick, E1C 9B6\
  ^2^Bedford Institute of Oceanography, Fisheries and Oceans Canada, 1 Challenger Dr., Dartmouth, Nova Scotia, B2Y 4A2\
  ^3^Nortwest Atlantic Fisheries Centre, Fisheries and Oceans Canada, 80 E White Hills Rd, St. John's, Newfoundland and Labrador, A1A 5J7\
  ^4^Saint Andrews Biological Station, Fisheries and Oceans Canada, 125 Marine Science Dr., St. Andrews, New Brunswick, E5B 0E4\
  ^5^Maurice Lamontagne Institute, Fisheries and Oceans Canada, 850 route de la Mer, Mont-Joli, Québec, QC G5H 3Z4\
  ^6^Freshwater Institute, Fisheries and Oceans Canada, 501 University Crescent, Winnipeg, Manitoba, R3T 2N6\
  ^7^Pacific Biological Station, Fisheries and Oceans Canada, 3190 Hammond Bay Road, Nanaimo, British Columbia, V9T 6N7\
french_address: |
  Science\
  Pêches et Océans Canada\
  Moncton, Nouveau-Brunswick, E1C 5K4, Canada\
phone: "(506) 377-9527"
author_footnote: "Email: Daniel.Ricard@dfo-mpo.gc.ca | telephone: (506) 377-9527"
abstract: |
  A three-day workshop was held in Moncton, New Brunswick, from January 31 to February 02 2023. The aim of the workshop was to examine and discuss best practices in the use of structures for age estimation. A summary of the different presentations is given along with a brief overview of discussions that took place during the workshop. A total of 41 recommended best practices are formulated to provide guidance for practitioners involved in the collection of otoliths and other hard parts, and in analyses of age estimates.
french_abstract: |
  Un atelier de trois jours s'est tenu à Moncton, au Nouveau-Brunswick, du 31 janvier au 2 février 2023. Le but de l'atelier était d'examiner et de discuter des meilleures pratiques en matière d'utilisation de structures pour l'estimation de l'âge. Un résumé des différentes présentations est donné ainsi qu'un bref aperçu des discussions qui ont eu lieu au cours de l'atelier. Un total de 41 recommandations des meilleures pratiques sont formulées pour guider les praticiens impliqués dans la collecte d'otolithes et d'autres parties dures, et dans l’analyse des estimations d’âge.
show_continued_text: true 
output:
 csasdown::techreport_pdf:
   french: false
   # copy_sty is a toggle to copy the style file from the csasdown package every time you compile
   # the document. If false, any changes you have made to the style file in your project
   # will remain between compilations. If true, your changes will be lost when you compile
   copy_sty: true
   # line_nums is a toggle to show line numbers on the left side of the page. 
   line_nums: false
   # line_nums_mod represents showing every Nth line if line_nums is true
   line_nums_mod: 1
   # lot_lof is a toggle to show/not show the lists of tables and figures at the
   # beginning of the document
   lot_lof: false
   # draft_watermark is a toggle to show/not show a DRAFT watermark across every page
   draft_watermark: true
   # highlight is the theme to use for code output. Must be one of the list given by:
   # pandoc --list-highlight-styles
   # which are:
   # pygments, tango, espresso, zenburn, kate, monochrome, breezedark, haddock
   # or the name of a custom *.latex file which is most easily made by copying one from 
   # the csasdown library 'themes' directory, this directory on your machine:
   # file.path(.libPaths(), "csasdown", "themes")
   # to your working directory (the one containing index.Rmd)
   # To change the foreground text color, change the RGB value in the line containing
   # 'DefineVerbatimEnvironment'
   # To change background color, change the RGB values in the line containing 'shadecolor'
   highlight: tango
type:
  techreport
# ------------
# End of options to set
knit: (function(input, ...) {
       csasdown::render('_bookdown.yml')
      })
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(rosettafish)
library(csasdown)
```
